print("Введите породу питомца")
breed = (input())
print("Введите имя питомца")
name = (input())
print("Введите возраст питомца")
age = (input())
print("Это", breed, "по кличке", name,". Возраст:", age)
